"""update generated_models table

Revision ID: 03b18df747c8
Revises: ee0b075c63cc
Create Date: 2025-05-06 21:42:03.195596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03b18df747c8'
down_revision: Union[str, None] = 'ee0b075c63cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_models', sa.Column('fields', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_models', 'fields')
    # ### end Alembic commands ###
