"""create system table

Revision ID: 5a271b80e680
Revises: e9db37d860bd
Create Date: 2025-05-06 19:09:44.862442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import sessionmaker
from models import System
from dotenv import load_dotenv
import os

# revision identifiers, used by Alembic.
revision: str = '5a271b80e680'
down_revision: Union[str, None] = 'e9db37d860bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    bind = op.get_bind()
    session = sessionmaker(bind=bind)()

    system1 = System(key="in_progress", value="false")
    system2 = System(key="progress_percent", value="0")

    session.add(system1)
    session.add(system2)
    session.commit()


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system')
    # ### end Alembic commands ###
