"""create airlines table

Revision ID: 687c55de131b
Revises: 
Create Date: 2025-05-03 14:40:24.783064

"""
from typing import Sequence, Union

import sqlalchemy as sa

import pandas as pd
from alembic import op
from sqlalchemy.orm import sessionmaker
from models import Airline

# revision identifiers, used by Alembic.
revision: str = '687c55de131b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airlines',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('airline', sa.String(), nullable=True),
                    sa.Column('flight_number', sa.String(), nullable=True),
                    sa.Column('airport_from', sa.String(), nullable=True),
                    sa.Column('airport_to', sa.String(), nullable=True),
                    sa.Column('day_of_week', sa.Integer(), nullable=True),
                    sa.Column('time', sa.Integer(), nullable=True),
                    sa.Column('length', sa.Integer(), nullable=True),
                    sa.Column('delay', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('airlines')
    # ### end Alembic commands ###
