"""update models table

Revision ID: b96953ce4f0e
Revises: 19a94b239146
Create Date: 2025-05-10 16:43:40.561876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b96953ce4f0e'
down_revision: Union[str, None] = '19a94b239146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_models', sa.Column('accuracy', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_models', 'accuracy')
    # ### end Alembic commands ###
