"""create users table

Revision ID: db7381ca63b3
Revises: 687c55de131b
Create Date: 2025-05-03 17:11:31.748298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import sessionmaker
from models import User
from dotenv import load_dotenv
import os

load_dotenv()

# revision identifiers, used by Alembic.
revision: str = 'db7381ca63b3'
down_revision: Union[str, None] = '687c55de131b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('nick', sa.String(), nullable=False),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.Column('admin', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('nick')
                    )
    # ### end Alembic commands ###

    # Connecting to a SQLAlchemy session
    bind = op.get_bind()
    session = sessionmaker(bind=bind)()

    user = User(email=os.getenv("ADMIN_EMAIL"), nick=os.getenv("ADMIN_NICK"), password=os.getenv("ADMIN_PASSWORD"), admin=True)

    session.add(user)
    session.commit()


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
