"""Update airline table

Revision ID: e9db37d860bd
Revises: db7381ca63b3
Create Date: 2025-05-05 20:44:10.580662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9db37d860bd'
down_revision: Union[str, None] = 'db7381ca63b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airlines', sa.Column('start_at', sa.String(), nullable=True))
    op.add_column('airlines', sa.Column('delay_probability', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('airlines', 'delay_probability')
    op.drop_column('airlines', 'start_at')
    # ### end Alembic commands ###
